//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octarines.Mars.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Octarines.Mars.Models.Resources.ValidationErrors", typeof(ValidationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions list must contain values.
        /// </summary>
        public static string InstructionsNull {
            get {
                return ResourceManager.GetString("InstructionsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plateau size string must contain a value..
        /// </summary>
        public static string PlateauSizeNullOrEmpty {
            get {
                return ResourceManager.GetString("PlateauSizeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plateua size must contain 2 values.
        /// </summary>
        public static string PlateauSizeNumber {
            get {
                return ResourceManager.GetString("PlateauSizeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X coordinate contains invalid character: &apos;{0}&apos;. Value must be an integer..
        /// </summary>
        public static string PlateauSizeXValue {
            get {
                return ResourceManager.GetString("PlateauSizeXValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y coordinate contains invalid character: &apos;{0}&apos;. Value must be an integer..
        /// </summary>
        public static string PlateauSizeYValue {
            get {
                return ResourceManager.GetString("PlateauSizeYValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover instruction string contains an invalid character: &apos;{0}&apos;.
        /// </summary>
        public static string RoverInstructionsChar {
            get {
                return ResourceManager.GetString("RoverInstructionsChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of instruction lines for navigation..
        /// </summary>
        public static string RoverInstructionsLines {
            get {
                return ResourceManager.GetString("RoverInstructionsLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover instruction string must contain a value..
        /// </summary>
        public static string RoverInstructionsNullOrEmpty {
            get {
                return ResourceManager.GetString("RoverInstructionsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions for rover &apos;{0}&apos; navigate it out of the defined plateau area..
        /// </summary>
        public static string RoverInstructionsOutOfArea {
            get {
                return ResourceManager.GetString("RoverInstructionsOutOfArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover bearing contains invalid character: &apos;{0}&apos;.
        /// </summary>
        public static string RoverPositionBearingChar {
            get {
                return ResourceManager.GetString("RoverPositionBearingChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover position must contain a value..
        /// </summary>
        public static string RoverPositionNullOrEmpty {
            get {
                return ResourceManager.GetString("RoverPositionNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover position must contain 3 values..
        /// </summary>
        public static string RoverPositionNumber {
            get {
                return ResourceManager.GetString("RoverPositionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover X position contains invalid character: &apos;{0}&apos;. Value must be an integer..
        /// </summary>
        public static string RoverPositionXValue {
            get {
                return ResourceManager.GetString("RoverPositionXValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover Y position contains invalid character: &apos;{0}&apos;. Value must be an integer..
        /// </summary>
        public static string RoverPositionYValue {
            get {
                return ResourceManager.GetString("RoverPositionYValue", resourceCulture);
            }
        }
    }
}
